REPO_NAME: demo-repo-1
REPO_DESCRIPTION: for demo purpose 1
TFC_WORKSPACE_NAME: workspace-1
TFC_WORKSPACE_TAGS_NAME: ["tag1"]
TFC_WORKSPACE_VARAIBLE_SET_NAME: Environment Variables 1
TFC_WORKSPACE_PROJECT_NAME: Project-1
NETWORK_SPOKE_MODULE: false
TFVARS_FILE: ["dev", "test"]
new_projects: ["example1", "example2"]
new_var_sets: ["New Variable Set 1", "New Variable Set 2"]