name: Create and Configure GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repository Name'
        required: true
      description:
        description: 'Repository Description'
        required: true
jobs:
  create-repo:
    runs-on: ubuntu-latest
    outputs:
      REPOSITORY_NAME: ${{ github.event.inputs.repoName }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Repository
      id: create_repo
      run: |
        REPO_NAME="${{ github.event.inputs.repoName }}"
        DESCRIPTION="${{ github.event.inputs.description }}"
        GH_PAT="${{ secrets.GH_PAT }}"
        
        # Create the repository using the GitHub API and set it as internal
        curl -X POST -H "Authorization: token $GH_PAT" \
          https://api.github.com/orgs/chvi-devops/repos -d "{\"name\":\"$REPO_NAME\",\"description\":\"$DESCRIPTION\",\"private\":true}"
        
        echo "::set-output name=repository_name::${REPO_NAME}"
      shell: bash

    - name: Show Repository Name
      run: echo "Repository Name: ${{ github.event.inputs.repoName }}"
