name: Create and Configure GitHub Repo

env:
  ORGANIZATION_NAME: 'chvi-devops'
  TEAM_NAME: 'TeamA'
  WORKSPACE_REPO_NAME: 'workspace-repo'
  
on:
  workflow_dispatch:
    inputs:
      # repoName:
      #   description: 'Repository Name'
      #   required: true
      # description:
      #   description: 'Repository Description'
      #   required: true
      workspaceName:
        description: 'TFC Workspace Name'
        required: true
      workspaceTagsName:
        description: 'Workspace tags name'
        required: true
      workspaceVariableSetName:
        description: 'Workspace Variable Set Name'
        required: true
      workspaceProjectName:
        description: 'Workspace Project Name'
        required: true
jobs:
  # create-repo:
  #   name: "Deploy New Repositories"
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check if Repository Already Exists
  #     id: check_repo
  #     run: |
  #       REPO_NAME="${{ github.event.inputs.repoName }}"
  #       ORG_NAME="${{ env.ORGANIZATION_NAME }}"
  #       GH_PAT="${{ secrets.GH_PAT }}"
          
  #       response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GH_PAT" \
  #         "https://api.github.com/repos/$ORG_NAME/$REPO_NAME")
  #       if [ "$response" == "200" ]; then
  #         echo "REPO_EXISTS=true" >> "$GITHUB_OUTPUT"
  #       else
  #         echo "REPO_EXISTS=false" >> "$GITHUB_OUTPUT"
  #       fi
  #     shell: bash

  #   - name: Stop Workflow If Repository Exist
  #     if: steps.check_repo.outputs.REPO_EXISTS == 'true'
  #     run: |
  #       echo "The repository already exist. Stopping the workflow."
  #       exit 1

  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Create Repository
  #     id: create_repo
  #     run: |
  #       REPO_NAME="${{ github.event.inputs.repoName }}"
  #       DESCRIPTION="${{ github.event.inputs.description }}"
  #       ORG_NAME="${{ env.ORGANIZATION_NAME }}"
  #       GH_PAT="${{ secrets.GH_PAT }}"
        
  #       # Create the repository using the GitHub API and set it as internal
  #       curl -X POST -H "Authorization: token $GH_PAT" \
  #         https://api.github.com/orgs/$ORG_NAME/repos -d "{\"name\":\"$REPO_NAME\",\"description\":\"$DESCRIPTION\"}"
  #       # https://api.github.com/orgs/$ORG_NAME/repos -d "{\"name\":\"$REPO_NAME\",\"description\":\"$DESCRIPTION\",\"private\":true}"
  #       echo "REPOSITORY_NAME=${{ github.event.inputs.repoName }}" >> "$GITHUB_ENV"
  #     shell: bash
    
  #   - name: Copy Template Files
  #     run: |
  #       REPO_NAME="${{ env.REPOSITORY_NAME }}"
  #       ORG_NAME="${{ env.ORGANIZATION_NAME }}"
    
  #       # Create a directory with the name of new repository created
  #       mkdir $REPO_NAME

  #       # Using cp command to copy all files and folders from from the 'templates' folder to the new repository folder
  #       cp -a templates/. ${{ github.workspace }}/$REPO_NAME/
  #     shell: bash


  #   - name: Add, Commit, and Push README.md
  #     run: |
  #       GH_PAT="${{ secrets.GH_PAT }}"
  #       REPO_NAME="${{ env.REPOSITORY_NAME }}"
  #       ORG_NAME="${{ env.ORGANIZATION_NAME }}"
  #       cd ${{ github.workspace }}/$REPO_NAME
  #       git config --global user.email "Demouser@gmail.com"
  #       git config --global user.name "DemoUser"
  #       git init
  #       git branch -M main
  #       git add README.md
  #       git commit -m "Added README.md"
  #       git remote add origin "https://$GH_PAT@github.com/$ORG_NAME/$REPO_NAME.git"
  #       git push origin main
  #       git branch development
  #       git checkout development
  #       git add .
  #       git commit -m "Added Initial files."
  #       git push origin development

  #   - name: Configure Branch Protection
  #     run: |
  #       REPO_NAME="${{ env.REPOSITORY_NAME }}"
  #       ORG_NAME="${{ env.ORGANIZATION_NAME }}"
  #       GH_PAT="${{ secrets.GH_PAT }}"
        
  #       # Enable branch protection for Main branch
  #       curl -X PUT -H "Authorization: token $GH_PAT" \
  #         "https://api.github.com/repos/$ORG_NAME/$REPO_NAME/branches/main/protection" -d '{
  #           "required_status_checks": null,
  #           "enforce_admins": null,
  #           "required_pull_request_reviews": {
  #             "dismiss_stale_reviews": false,
  #             "require_code_owner_reviews": false,
  #             "required_approving_review_count": 1
  #           },
  #           "restrictions": null,
  #           "required_linear_history": false,
  #           "allow_force_pushes": false,
  #           "allow_deletions": false
  #         }'
        
  #       # Enable branch protection for Development branch
  #       curl -X PUT -H "Authorization: token $GH_PAT" \
  #         "https://api.github.com/repos/$ORG_NAME/$REPO_NAME/branches/development/protection" -d '{
  #           "required_status_checks": null,
  #           "enforce_admins": null,
  #           "required_pull_request_reviews": {
  #             "dismiss_stale_reviews": false,
  #             "require_code_owner_reviews": false,
  #             "required_approving_review_count": 1
  #           },
  #           "restrictions": null,
  #           "required_linear_history": false,
  #           "allow_force_pushes": false,
  #           "allow_deletions": false
  #         }'
  #     shell: bash
  
  #   - name: Add TeamA as a Reviewer Team
  #     run: |
  #       REPO_NAME="${{ env.REPOSITORY_NAME }}"
  #       ORG_NAME="${{ env.ORGANIZATION_NAME }}"
  #       GH_PAT="${{ secrets.GH_PAT }}"
  #       GH_PAT="${{ secrets.GH_PAT }}"
  #       TEAM_SLUG_NAME=$(echo "${{ env.TEAM_NAME }}" | tr '[:upper:]' '[:lower:]')
  #       # Add TeamA as a possible reviewer team to the repository
  #       curl -X PUT -H "Authorization: token $GH_PAT" \
  #       "https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_SLUG_NAME/repos/$ORG_NAME/$REPO_NAME" -d '{
  #       "permission": "triage"
  #       }'
  #     shell: bash

  create-workspace:
    # needs: create-repo
    name: "Create new tfc-workspace"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone the worskspace repo
      run: |
        GH_PAT="${{ secrets.GH_PAT }}"
        REPO_NAME="${{ env.WORKSPACE_REPO_NAME }}"
        ORG_NAME="${{ env.ORGANIZATION_NAME }}"
        WORKSPACE_NAME="${{ github.event.inputs.workspaceName }}"
        git clone https://$GH_PAT@github.com/$ORG_NAME/$REPO_NAME.git
        cd ${{ github.workspace }}/$REPO_NAME
        git config --global user.email "Demouser@gmail.com"
        git config --global user.name "DemoUser"
        git checkout development
        git branch feat-$WORKSPACE_NAME
        git checkout feat-$WORKSPACE_NAME
        
    - name: Manipulate and Update Workspace Object
      run: |
        WORKSPACE_NAME="${{ github.event.inputs.workspaceName }}"
        REPO_NAME="${{ env.WORKSPACE_REPO_NAME }}"
        ls
        # Read the abc-workspace object from template-workspace.tf
        TEMPLATE_WORKSPACE_OBJECT=$(cat ${{ github.workspace }}/template-workspaces.tfvars)

        # Manipulate the values based on input parameters
        NEW_NAME="${{ github.event.inputs.workspaceName }}"
        NEW_TAG_NAMES="${{ github.event.inputs.workspaceTagsName }}"
        NEW_VARIABLE_SET_NAME="${{ github.event.inputs.workspaceVariableSetName }}"
        NEW_PROJECT_NAME="${{ github.event.inputs.workspaceProjectName }}"

        # Rename the abc-workspace object with the new workspace name
        MODIFIED_WORKSPACE_OBJECT=$(echo "$TEMPLATE_WORKSPACE_OBJECT" | jq --arg NEW_NAME "$NEW_NAME" \
            --arg NEW_KEY "$NEW_NAME" \
            --arg NEW_TAG_NAMES "$NEW_TAG_NAMES" \
            --arg NEW_VARIABLE_SET_NAME "$NEW_VARIABLE_SET_NAME" \
            --arg NEW_PROJECT_NAME "$NEW_PROJECT_NAME" \
            '. + {($NEW_NAME): .abc-workspace | .name = $NEW_NAME | .key = $NEW_NAME | .tag_names = $NEW_TAG_NAMES | .variable_set_name = $NEW_VARIABLE_SET_NAME | .project_name = $NEW_PROJECT_NAME} | del(.["abc-workspace"])')

        # Update workspaces.tfvars with the modified workspace object
        TFE_TFVARS_FILE="${{ github.workspace }}/$REPO_NAME/workspaces.tfvars"
        TFE_TFVARS_JSON=$(cat "$TFE_TFVARS_FILE" | jq .)
        UPDATED_TFE_TFVARS_JSON=$(echo "$TFE_TFVARS_JSON" | jq --argjson MODIFIED_WORKSPACE_OBJECT "$MODIFIED_WORKSPACE_OBJECT" '.workspaces += $MODIFIED_WORKSPACE_OBJECT')

        # Write the updated JSON structure back to workspaces.tfvars
        echo "$UPDATED_TFE_TFVARS_JSON" > "$TFE_TFVARS_FILE"

        # Commit and push changes to the workspace-repo repository
        cd ${{ github.workspace }}/$REPO_NAME
        git add .
        git commit -m "Updated workspaces.tfvars file"
        git push origin feat-$WORKSPACE_NAME
      shell: bash
