name: Create and Configure GitHub Repo

env:
  ORGANIZATION_NAME: 'chvi-devops'
  TEAM_NAME: 'TeamA'
  
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repository Name'
        required: true
      description:
        description: 'Repository Description'
        required: true
jobs:
  CreateRepo:
    name: "Deploy New Repositories"
    runs-on: ubuntu-latest
    steps:
    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Check if Repository Already Exists and Stop Workflow If Repository Exist
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        REPO_NAME="${{ github.event.inputs.repoName }}"
        ORG_NAME="${{ env.ORGANIZATION_NAME }}"

        echo "REPOSITORY_NAME=$REPO_NAME" >> "$GITHUB_ENV"

        if gh api repos/$ORG_NAME/$REPO_NAME --silent 2>/dev/null; then
          echo "Repository $ORG_NAME/$REPO_NAME exists."
          exit 1
        else
          echo "Repository $ORG_NAME/$REPO_NAME does not exist."
        fi
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Repository
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        DESCRIPTION="${{ github.event.inputs.description }}"
        REPO_NAME="${{ env.REPOSITORY_NAME }}"
        ORG_NAME="${{ env.ORGANIZATION_NAME }}"

        gh repo create chvi-devops/$REPO_NAME --public --description=$DESCRIPTION --include-all-branches --template=template-repo 