name: Create and Configure GitHub Repo

env:
  ORGANIZATION_NAME: 'chvi-devops'
  TEAM_NAME: 'TeamA'
  
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repository Name'
        required: true
      description:
        description: 'Repository Description'
        required: true
jobs:
  CreateRepo:
    name: "Deploy New Repositories"
    runs-on: ubuntu-latest
    steps:
    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Check if Repository Already Exists
      id: check_repo
      run: |
        REPO_NAME="${{ github.event.inputs.repoName }}"
        ORG_NAME="${{ env.ORGANIZATION_NAME }}"
        GITHUB_TOKEN="${{ steps.generate_token.outputs.token }}"

        echo "REPOSITORY_NAME=$REPO_NAME" >> "$GITHUB_ENV"
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> "$GITHUB_ENV"

        response=$(gh api --method GET \
                      -H "Accept: application/vnd.github+json" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      repos/$ORG_NAME/$REPO_NAME --jq '. | .status')

        if [ "$response" == "200" ]; then
          echo "REPO_EXISTS=true" >> "$GITHUB_OUTPUT"
        else
          echo "REPO_EXISTS=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Stop Workflow If Repository Exist
      if: steps.check_repo.outputs.REPO_EXISTS == 'true'
      run: |
        echo "The repository already exist. Stopping the workflow."
        exit 1

    - name: Checkout code
      uses: actions/checkout@v2
