name: Create and Configure GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repository Name'
        required: true
      description:
        description: 'Repository Description'
        required: true
jobs:
  create-repo:
    runs-on: ubuntu-latest
    outputs:
      REPOSITORY_NAME: ${{ github.event.inputs.repoName }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Repository
      id: create_repo
      run: |
        REPO_NAME="${{ github.event.inputs.repoName }}"
        DESCRIPTION="${{ github.event.inputs.description }}"
        GH_PAT="${{ secrets.GH_PAT }}"
        
        # Create the repository using the GitHub API and set it as internal
        curl -X POST -H "Authorization: token $GH_PAT" \
          https://api.github.com/orgs/chvi-devops/repos -d "{\"name\":\"$REPO_NAME\",\"description\":\"$DESCRIPTION\",\"private\":true}"
        
        echo "REPOSITORY_NAME=${{ github.event.inputs.repoName }}" >> "$GITHUB_ENV"
      shell: bash
    
    - name: Output Repo name
      id: output
      run: |
        echo "REPO_NAME=${{ env.REPO_NAME }}" >> "$GITHUB_OUTPUT"

    - name: Copy README.md
      run: |
        REPO_NAME="${{ env.REPOSITORY_NAME }}"
        mkdir $REPO_NAME
        cp README.md ${{ github.workspace }}/$REPO_NAME

    - name: Add, Commit, and Push README.md
      run: |
        REPO_NAME="${{ env.REPOSITORY_NAME }}"
        cd ${{ github.workspace }}/$REPO_NAME
        git config --global user.email "vishalchaudhary@gmail.com"
        git config --global user.name "Vishal Chaudhary"
        git init
        git add .
        git commit -m "Add README.md"
        git remote add origin "https://github.com/chvi-devops/$REPO_NAME.git"
        git branch -M main
        git branch development
        git push https://$GH_PAT@github.com/chvi-devops/$REPO_NAME.git HEAD:main
        
    # - name: Add Main and Development Branches
    #   run: |
    #     REPO_NAME="${{ env.REPOSITORY_NAME }}"
    #     GH_PAT="${{ secrets.GH_PAT }}"
        
    #     # Add Main branch
    #     curl -X POST -H "Authorization: token $GH_PAT" \
    #       "https://api.github.com/repos/chvi-devops/$REPO_NAME/git/refs" -d "{\"ref\":\"refs/heads/main\",\"sha\":\"$(curl -s -H 'Authorization: token $GH_PAT' https://api.github.com/repos/your-org/$REPO_NAME/git/refs/heads/main | jq -r '.object.sha')\"}"
        
    #     # Add Development branch
    #     curl -X POST -H "Authorization: token $GH_PAT" \
    #       "https://api.github.com/repos/chvi-devops/$REPO_NAME/git/refs" -d "{\"ref\":\"refs/heads/development\",\"sha\":\"$(curl -s -H 'Authorization: token $GH_PAT' https://api.github.com/repos/your-org/$REPO_NAME/git/refs/heads/main | jq -r '.object.sha')\"}"
    #   shell: bash

    - name: Configure Branch Protection
      run: |
        REPO_NAME="${{ env.REPOSITORY_NAME }}"
        GH_PAT="${{ secrets.GH_PAT }}"
        
        # Enable branch protection for Main branch
        curl -X PUT -H "Authorization: token $GH_PAT" \
          "https://api.github.com/repos/chvi-devops/$REPO_NAME/branches/main/protection" -d '{
            "required_status_checks": null,
            "enforce_admins": null,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false,
              "required_approving_review_count": 1
            },
            "restrictions": null,
            "required_linear_history": false,
            "allow_force_pushes": false,
            "allow_deletions": false
          }'
        
        # Enable branch protection for Development branch
        curl -X PUT -H "Authorization: token $GH_PAT" \
          "https://api.github.com/repos/chvi-devops/$REPO_NAME/branches/development/protection" -d '{
            "required_status_checks": null,
            "enforce_admins": null,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false,
              "required_approving_review_count": 1
            },
            "restrictions": null,
            "required_linear_history": false,
            "allow_force_pushes": false,
            "allow_deletions": false
          }'
      shell: bash

